//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 08:41:21 PM CET 
//


package pl.szaqku.awir.payment.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentRefusalResponseDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentRefusalResponseDocumentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BankPaymentRefusalIdentifier" type="{http://services.szaqku.pl}max35Identifier"/&gt;
 *         &lt;element ref="{http://services.szaqku.pl}PaymentRefusalResponseInfoDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentRefusalResponseDocumentType", propOrder = {
    "bankPaymentRefusalIdentifier",
    "paymentRefusalResponseInfoDetails"
})
public class PaymentRefusalResponseDocumentType {

    @XmlElement(name = "BankPaymentRefusalIdentifier", required = true)
    protected String bankPaymentRefusalIdentifier;
    @XmlElement(name = "PaymentRefusalResponseInfoDetails", namespace = "http://services.szaqku.pl", required = true)
    protected PaymentRefusalResponseInfoDetails paymentRefusalResponseInfoDetails;

    /**
     * Gets the value of the bankPaymentRefusalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankPaymentRefusalIdentifier() {
        return bankPaymentRefusalIdentifier;
    }

    /**
     * Sets the value of the bankPaymentRefusalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankPaymentRefusalIdentifier(String value) {
        this.bankPaymentRefusalIdentifier = value;
    }

    /**
     * Gets the value of the paymentRefusalResponseInfoDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRefusalResponseInfoDetails }
     *     
     */
    public PaymentRefusalResponseInfoDetails getPaymentRefusalResponseInfoDetails() {
        return paymentRefusalResponseInfoDetails;
    }

    /**
     * Sets the value of the paymentRefusalResponseInfoDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRefusalResponseInfoDetails }
     *     
     */
    public void setPaymentRefusalResponseInfoDetails(PaymentRefusalResponseInfoDetails value) {
        this.paymentRefusalResponseInfoDetails = value;
    }

}
