//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 08:41:21 PM CET 
//


package pl.szaqku.awir.payment.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://services.szaqku.pl}PaymentHeader"/&gt;
 *         &lt;element ref="{http://services.szaqku.pl}PaymentLineItem" maxOccurs="unbounded"/&gt;
 *         &lt;element name="PaymentSummary" type="{http://services.szaqku.pl}PaymentSummaryType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentHeader",
    "paymentLineItem",
    "paymentSummary"
})
@XmlRootElement(name = "PaymentDocument")
public class PaymentDocument {

    @XmlElement(name = "PaymentHeader", namespace = "http://services.szaqku.pl", required = true)
    protected PaymentHeader paymentHeader;
    @XmlElement(name = "PaymentLineItem", namespace = "http://services.szaqku.pl", required = true)
    protected List<PaymentLineItem> paymentLineItem;
    @XmlElement(name = "PaymentSummary")
    protected PaymentSummaryType paymentSummary;

    /**
     * Gets the value of the paymentHeader property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentHeader }
     *     
     */
    public PaymentHeader getPaymentHeader() {
        return paymentHeader;
    }

    /**
     * Sets the value of the paymentHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentHeader }
     *     
     */
    public void setPaymentHeader(PaymentHeader value) {
        this.paymentHeader = value;
    }

    /**
     * Gets the value of the paymentLineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentLineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentLineItem }
     * 
     * 
     */
    public List<PaymentLineItem> getPaymentLineItem() {
        if (paymentLineItem == null) {
            paymentLineItem = new ArrayList<PaymentLineItem>();
        }
        return this.paymentLineItem;
    }

    /**
     * Gets the value of the paymentSummary property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentSummaryType }
     *     
     */
    public PaymentSummaryType getPaymentSummary() {
        return paymentSummary;
    }

    /**
     * Sets the value of the paymentSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentSummaryType }
     *     
     */
    public void setPaymentSummary(PaymentSummaryType value) {
        this.paymentSummary = value;
    }

}
