//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 08:41:21 PM CET 
//


package pl.szaqku.awir.payment.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NominalName" type="{http://services.szaqku.pl}max35text"/&gt;
 *         &lt;element name="NominalNumber" type="{http://services.szaqku.pl}Decimal6.0"/&gt;
 *         &lt;element name="NominalValue" type="{http://services.szaqku.pl}AmountType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nominalName",
    "nominalNumber",
    "nominalValue"
})
@XmlRootElement(name = "Denominations")
public class Denominations {

    @XmlElement(name = "NominalName", required = true)
    protected Max35Text nominalName;
    @XmlElement(name = "NominalNumber", required = true)
    protected BigDecimal nominalNumber;
    @XmlElement(name = "NominalValue")
    protected AmountType nominalValue;

    /**
     * Gets the value of the nominalName property.
     * 
     * @return
     *     possible object is
     *     {@link Max35Text }
     *     
     */
    public Max35Text getNominalName() {
        return nominalName;
    }

    /**
     * Sets the value of the nominalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Max35Text }
     *     
     */
    public void setNominalName(Max35Text value) {
        this.nominalName = value;
    }

    /**
     * Gets the value of the nominalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNominalNumber() {
        return nominalNumber;
    }

    /**
     * Sets the value of the nominalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNominalNumber(BigDecimal value) {
        this.nominalNumber = value;
    }

    /**
     * Gets the value of the nominalValue property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getNominalValue() {
        return nominalValue;
    }

    /**
     * Sets the value of the nominalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setNominalValue(AmountType value) {
        this.nominalValue = value;
    }

}
